swagger: "2.0"
info:
  title: pgEdge API
  version: 1.0.0
paths:
  /oauth/token:
    post:
      summary: Get OAuth Token
      description: Request an OAuth token for authentication
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: client_id
          in: formData
          type: string
          required: true
        - name: client_secret
          in: formData
          type: string
          required: true
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              access_token:
                type: string
              expires_in:
                type: integer
              token_type:
                type: string
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /databases:
    get:
      summary: Get All Databases
      description: Retrieve a list of all databases
      parameters:
        - name: Authorization
          in: header
          type: string
          format: Bearer {access_token}
          required: true
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Database'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /databases/{id}:
    get:
      summary: Get Database by ID
      description: Retrieve detailed information about a specific database
      parameters:
        - name: id
          in: path
          type: string
          format: uuid
          required: true
        - name: Authorization
          in: header
          type: string
          format: Bearer {access_token}
          required: true
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/DatabaseDetails'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

definitions:
  Database:
    type: object
    properties:
      created_at:
        type: string
        format: date-time
      domain:
        type: string
      id:
        type: string
        format: uuid
      name:
        type: string
      nodes:
        type: array
        items:
          $ref: '#/definitions/Node'
      status:
        type: string
      updated_at:
        type: string
        format: date-time

  DatabaseDetails:
    type: object
    properties:
      components:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            release_date:
              type: string
              format: date
            status:
              type: string
            version:
              type: string
      created_at:
        type: string
        format: date-time
      id:
        type: string
        format: uuid
      name:
        type: string
      nodes:
        type: array
        items:
          $ref: '#/definitions/Node'
      pg_version:
        type: string
      roles:
        type: array
        items:
          type: object
          properties:
            bypass_rls:
              type: boolean
            connection_limit:
              type: integer
            create_db:
              type: boolean
            create_role:
              type: boolean
            inherit:
              type: boolean
            login:
              type: boolean
            name:
              type: string
            replication:
              type: boolean
            superuser:
              type: boolean
      status:
        type: string
      storage_used:
        type: integer
      tables:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            primary_key:
              type: array
              items:
                type: string
            replication_sets:
              type: object
            schema:
              type: string
            status:
              type: array
              items:
                type: object
                properties:
                  aligned:
                    type: boolean
                  node_name:
                    type: string
                  present:
                    type: boolean
                  replicating:
                    type: boolean
      updated_at:
        type: string
        format: date-time

  Node:
    type: object
    properties:
      connection:
        type: object
        properties:
          database:
            type: string
          host:
            type: string
          password:
            type: string
          port:
            type: integer
          username:
            type: string
      location:
        type: object
        properties:
          code:
            type: string
          country:
            type: string
          latitude:
            type: number
          longitude:
            type: number
          name:
            type: string
          region:
            type: string
          region_code:
            type: string
      name:
        type: string
