// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TableStatus table status
//
// swagger:model TableStatus
type TableStatus struct {

	// aligned
	Aligned bool `json:"aligned,omitempty"`

	// node name
	NodeName string `json:"node_name,omitempty"`

	// present
	Present bool `json:"present,omitempty"`

	// replicating
	Replicating bool `json:"replicating,omitempty"`
}

// Validate validates this table status
func (m *TableStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this table status based on context it is used
func (m *TableStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TableStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TableStatus) UnmarshalBinary(b []byte) error {
	var res TableStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
