// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pgEdge/terraform-provider-pgedge/client/models"
)

// DeleteClustersIDReader is a Reader for the DeleteClustersID structure.
type DeleteClustersIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteClustersIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteClustersIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteClustersIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteClustersIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteClustersIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /clusters/{id}] DeleteClustersID", response, response.Code())
	}
}

// NewDeleteClustersIDNoContent creates a DeleteClustersIDNoContent with default headers values
func NewDeleteClustersIDNoContent() *DeleteClustersIDNoContent {
	return &DeleteClustersIDNoContent{}
}

/*
DeleteClustersIDNoContent describes a response with status code 204, with default header values.

No Content (successful deletion)
*/
type DeleteClustersIDNoContent struct {
}

// IsSuccess returns true when this delete clusters Id no content response has a 2xx status code
func (o *DeleteClustersIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete clusters Id no content response has a 3xx status code
func (o *DeleteClustersIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete clusters Id no content response has a 4xx status code
func (o *DeleteClustersIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete clusters Id no content response has a 5xx status code
func (o *DeleteClustersIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete clusters Id no content response a status code equal to that given
func (o *DeleteClustersIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete clusters Id no content response
func (o *DeleteClustersIDNoContent) Code() int {
	return 204
}

func (o *DeleteClustersIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{id}][%d] deleteClustersIdNoContent ", 204)
}

func (o *DeleteClustersIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /clusters/{id}][%d] deleteClustersIdNoContent ", 204)
}

func (o *DeleteClustersIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteClustersIDBadRequest creates a DeleteClustersIDBadRequest with default headers values
func NewDeleteClustersIDBadRequest() *DeleteClustersIDBadRequest {
	return &DeleteClustersIDBadRequest{}
}

/*
DeleteClustersIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteClustersIDBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete clusters Id bad request response has a 2xx status code
func (o *DeleteClustersIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete clusters Id bad request response has a 3xx status code
func (o *DeleteClustersIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete clusters Id bad request response has a 4xx status code
func (o *DeleteClustersIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete clusters Id bad request response has a 5xx status code
func (o *DeleteClustersIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete clusters Id bad request response a status code equal to that given
func (o *DeleteClustersIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete clusters Id bad request response
func (o *DeleteClustersIDBadRequest) Code() int {
	return 400
}

func (o *DeleteClustersIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{id}][%d] deleteClustersIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteClustersIDBadRequest) String() string {
	return fmt.Sprintf("[DELETE /clusters/{id}][%d] deleteClustersIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteClustersIDBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteClustersIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteClustersIDUnauthorized creates a DeleteClustersIDUnauthorized with default headers values
func NewDeleteClustersIDUnauthorized() *DeleteClustersIDUnauthorized {
	return &DeleteClustersIDUnauthorized{}
}

/*
DeleteClustersIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteClustersIDUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete clusters Id unauthorized response has a 2xx status code
func (o *DeleteClustersIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete clusters Id unauthorized response has a 3xx status code
func (o *DeleteClustersIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete clusters Id unauthorized response has a 4xx status code
func (o *DeleteClustersIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete clusters Id unauthorized response has a 5xx status code
func (o *DeleteClustersIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete clusters Id unauthorized response a status code equal to that given
func (o *DeleteClustersIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete clusters Id unauthorized response
func (o *DeleteClustersIDUnauthorized) Code() int {
	return 401
}

func (o *DeleteClustersIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{id}][%d] deleteClustersIdUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteClustersIDUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /clusters/{id}][%d] deleteClustersIdUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteClustersIDUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteClustersIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteClustersIDInternalServerError creates a DeleteClustersIDInternalServerError with default headers values
func NewDeleteClustersIDInternalServerError() *DeleteClustersIDInternalServerError {
	return &DeleteClustersIDInternalServerError{}
}

/*
DeleteClustersIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteClustersIDInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete clusters Id internal server error response has a 2xx status code
func (o *DeleteClustersIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete clusters Id internal server error response has a 3xx status code
func (o *DeleteClustersIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete clusters Id internal server error response has a 4xx status code
func (o *DeleteClustersIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete clusters Id internal server error response has a 5xx status code
func (o *DeleteClustersIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete clusters Id internal server error response a status code equal to that given
func (o *DeleteClustersIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete clusters Id internal server error response
func (o *DeleteClustersIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteClustersIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /clusters/{id}][%d] deleteClustersIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteClustersIDInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /clusters/{id}][%d] deleteClustersIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteClustersIDInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteClustersIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
