// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pgEdge/terraform-provider-pgedge/client/models"
)

// GetClustersReader is a Reader for the GetClusters structure.
type GetClustersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClustersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClustersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetClustersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetClustersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /clusters] GetClusters", response, response.Code())
	}
}

// NewGetClustersOK creates a GetClustersOK with default headers values
func NewGetClustersOK() *GetClustersOK {
	return &GetClustersOK{}
}

/*
GetClustersOK describes a response with status code 200, with default header values.

Response containing an array of clusters.
*/
type GetClustersOK struct {
	Payload []*models.Cluster
}

// IsSuccess returns true when this get clusters o k response has a 2xx status code
func (o *GetClustersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get clusters o k response has a 3xx status code
func (o *GetClustersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get clusters o k response has a 4xx status code
func (o *GetClustersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get clusters o k response has a 5xx status code
func (o *GetClustersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get clusters o k response a status code equal to that given
func (o *GetClustersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get clusters o k response
func (o *GetClustersOK) Code() int {
	return 200
}

func (o *GetClustersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /clusters][%d] getClustersOK %s", 200, payload)
}

func (o *GetClustersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /clusters][%d] getClustersOK %s", 200, payload)
}

func (o *GetClustersOK) GetPayload() []*models.Cluster {
	return o.Payload
}

func (o *GetClustersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClustersBadRequest creates a GetClustersBadRequest with default headers values
func NewGetClustersBadRequest() *GetClustersBadRequest {
	return &GetClustersBadRequest{}
}

/*
GetClustersBadRequest describes a response with status code 400, with default header values.

Bad request.
*/
type GetClustersBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get clusters bad request response has a 2xx status code
func (o *GetClustersBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get clusters bad request response has a 3xx status code
func (o *GetClustersBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get clusters bad request response has a 4xx status code
func (o *GetClustersBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get clusters bad request response has a 5xx status code
func (o *GetClustersBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get clusters bad request response a status code equal to that given
func (o *GetClustersBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get clusters bad request response
func (o *GetClustersBadRequest) Code() int {
	return 400
}

func (o *GetClustersBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /clusters][%d] getClustersBadRequest %s", 400, payload)
}

func (o *GetClustersBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /clusters][%d] getClustersBadRequest %s", 400, payload)
}

func (o *GetClustersBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetClustersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClustersUnauthorized creates a GetClustersUnauthorized with default headers values
func NewGetClustersUnauthorized() *GetClustersUnauthorized {
	return &GetClustersUnauthorized{}
}

/*
GetClustersUnauthorized describes a response with status code 401, with default header values.

Authorization information is missing or invalid.
*/
type GetClustersUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this get clusters unauthorized response has a 2xx status code
func (o *GetClustersUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get clusters unauthorized response has a 3xx status code
func (o *GetClustersUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get clusters unauthorized response has a 4xx status code
func (o *GetClustersUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get clusters unauthorized response has a 5xx status code
func (o *GetClustersUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get clusters unauthorized response a status code equal to that given
func (o *GetClustersUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get clusters unauthorized response
func (o *GetClustersUnauthorized) Code() int {
	return 401
}

func (o *GetClustersUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /clusters][%d] getClustersUnauthorized %s", 401, payload)
}

func (o *GetClustersUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /clusters][%d] getClustersUnauthorized %s", 401, payload)
}

func (o *GetClustersUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetClustersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
