// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pgEdge/terraform-provider-pgedge/models"
)

// GetDatabasesIDReader is a Reader for the GetDatabasesID structure.
type GetDatabasesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDatabasesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDatabasesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetDatabasesIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDatabasesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /databases/{id}] GetDatabasesID", response, response.Code())
	}
}

// NewGetDatabasesIDOK creates a GetDatabasesIDOK with default headers values
func NewGetDatabasesIDOK() *GetDatabasesIDOK {
	return &GetDatabasesIDOK{}
}

/*
GetDatabasesIDOK describes a response with status code 200, with default header values.

Successful response
*/
type GetDatabasesIDOK struct {
	Payload *models.DatabaseDetails
}

// IsSuccess returns true when this get databases Id o k response has a 2xx status code
func (o *GetDatabasesIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get databases Id o k response has a 3xx status code
func (o *GetDatabasesIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get databases Id o k response has a 4xx status code
func (o *GetDatabasesIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get databases Id o k response has a 5xx status code
func (o *GetDatabasesIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get databases Id o k response a status code equal to that given
func (o *GetDatabasesIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get databases Id o k response
func (o *GetDatabasesIDOK) Code() int {
	return 200
}

func (o *GetDatabasesIDOK) Error() string {
	return fmt.Sprintf("[GET /databases/{id}][%d] getDatabasesIdOK  %+v", 200, o.Payload)
}

func (o *GetDatabasesIDOK) String() string {
	return fmt.Sprintf("[GET /databases/{id}][%d] getDatabasesIdOK  %+v", 200, o.Payload)
}

func (o *GetDatabasesIDOK) GetPayload() *models.DatabaseDetails {
	return o.Payload
}

func (o *GetDatabasesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DatabaseDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDatabasesIDUnauthorized creates a GetDatabasesIDUnauthorized with default headers values
func NewGetDatabasesIDUnauthorized() *GetDatabasesIDUnauthorized {
	return &GetDatabasesIDUnauthorized{}
}

/*
GetDatabasesIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetDatabasesIDUnauthorized struct {
}

// IsSuccess returns true when this get databases Id unauthorized response has a 2xx status code
func (o *GetDatabasesIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get databases Id unauthorized response has a 3xx status code
func (o *GetDatabasesIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get databases Id unauthorized response has a 4xx status code
func (o *GetDatabasesIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get databases Id unauthorized response has a 5xx status code
func (o *GetDatabasesIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get databases Id unauthorized response a status code equal to that given
func (o *GetDatabasesIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get databases Id unauthorized response
func (o *GetDatabasesIDUnauthorized) Code() int {
	return 401
}

func (o *GetDatabasesIDUnauthorized) Error() string {
	return fmt.Sprintf("[GET /databases/{id}][%d] getDatabasesIdUnauthorized ", 401)
}

func (o *GetDatabasesIDUnauthorized) String() string {
	return fmt.Sprintf("[GET /databases/{id}][%d] getDatabasesIdUnauthorized ", 401)
}

func (o *GetDatabasesIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDatabasesIDInternalServerError creates a GetDatabasesIDInternalServerError with default headers values
func NewGetDatabasesIDInternalServerError() *GetDatabasesIDInternalServerError {
	return &GetDatabasesIDInternalServerError{}
}

/*
GetDatabasesIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetDatabasesIDInternalServerError struct {
}

// IsSuccess returns true when this get databases Id internal server error response has a 2xx status code
func (o *GetDatabasesIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get databases Id internal server error response has a 3xx status code
func (o *GetDatabasesIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get databases Id internal server error response has a 4xx status code
func (o *GetDatabasesIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get databases Id internal server error response has a 5xx status code
func (o *GetDatabasesIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get databases Id internal server error response a status code equal to that given
func (o *GetDatabasesIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get databases Id internal server error response
func (o *GetDatabasesIDInternalServerError) Code() int {
	return 500
}

func (o *GetDatabasesIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /databases/{id}][%d] getDatabasesIdInternalServerError ", 500)
}

func (o *GetDatabasesIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /databases/{id}][%d] getDatabasesIdInternalServerError ", 500)
}

func (o *GetDatabasesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
