// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pgEdge/terraform-provider-pgedge/models"
)

// GetClustersReader is a Reader for the GetClusters structure.
type GetClustersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClustersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClustersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetClustersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetClustersInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /clusters] GetClusters", response, response.Code())
	}
}

// NewGetClustersOK creates a GetClustersOK with default headers values
func NewGetClustersOK() *GetClustersOK {
	return &GetClustersOK{}
}

/*
GetClustersOK describes a response with status code 200, with default header values.

Successful response
*/
type GetClustersOK struct {
	Payload []*models.ClusterDetails
}

// IsSuccess returns true when this get clusters o k response has a 2xx status code
func (o *GetClustersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get clusters o k response has a 3xx status code
func (o *GetClustersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get clusters o k response has a 4xx status code
func (o *GetClustersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get clusters o k response has a 5xx status code
func (o *GetClustersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get clusters o k response a status code equal to that given
func (o *GetClustersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get clusters o k response
func (o *GetClustersOK) Code() int {
	return 200
}

func (o *GetClustersOK) Error() string {
	return fmt.Sprintf("[GET /clusters][%d] getClustersOK  %+v", 200, o.Payload)
}

func (o *GetClustersOK) String() string {
	return fmt.Sprintf("[GET /clusters][%d] getClustersOK  %+v", 200, o.Payload)
}

func (o *GetClustersOK) GetPayload() []*models.ClusterDetails {
	return o.Payload
}

func (o *GetClustersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClustersUnauthorized creates a GetClustersUnauthorized with default headers values
func NewGetClustersUnauthorized() *GetClustersUnauthorized {
	return &GetClustersUnauthorized{}
}

/*
GetClustersUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetClustersUnauthorized struct {
}

// IsSuccess returns true when this get clusters unauthorized response has a 2xx status code
func (o *GetClustersUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get clusters unauthorized response has a 3xx status code
func (o *GetClustersUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get clusters unauthorized response has a 4xx status code
func (o *GetClustersUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get clusters unauthorized response has a 5xx status code
func (o *GetClustersUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get clusters unauthorized response a status code equal to that given
func (o *GetClustersUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get clusters unauthorized response
func (o *GetClustersUnauthorized) Code() int {
	return 401
}

func (o *GetClustersUnauthorized) Error() string {
	return fmt.Sprintf("[GET /clusters][%d] getClustersUnauthorized ", 401)
}

func (o *GetClustersUnauthorized) String() string {
	return fmt.Sprintf("[GET /clusters][%d] getClustersUnauthorized ", 401)
}

func (o *GetClustersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetClustersInternalServerError creates a GetClustersInternalServerError with default headers values
func NewGetClustersInternalServerError() *GetClustersInternalServerError {
	return &GetClustersInternalServerError{}
}

/*
GetClustersInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetClustersInternalServerError struct {
}

// IsSuccess returns true when this get clusters internal server error response has a 2xx status code
func (o *GetClustersInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get clusters internal server error response has a 3xx status code
func (o *GetClustersInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get clusters internal server error response has a 4xx status code
func (o *GetClustersInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get clusters internal server error response has a 5xx status code
func (o *GetClustersInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get clusters internal server error response a status code equal to that given
func (o *GetClustersInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get clusters internal server error response
func (o *GetClustersInternalServerError) Code() int {
	return 500
}

func (o *GetClustersInternalServerError) Error() string {
	return fmt.Sprintf("[GET /clusters][%d] getClustersInternalServerError ", 500)
}

func (o *GetClustersInternalServerError) String() string {
	return fmt.Sprintf("[GET /clusters][%d] getClustersInternalServerError ", 500)
}

func (o *GetClustersInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
