// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetClustersParams creates a new GetClustersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClustersParams() *GetClustersParams {
	return &GetClustersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClustersParamsWithTimeout creates a new GetClustersParams object
// with the ability to set a timeout on a request.
func NewGetClustersParamsWithTimeout(timeout time.Duration) *GetClustersParams {
	return &GetClustersParams{
		timeout: timeout,
	}
}

// NewGetClustersParamsWithContext creates a new GetClustersParams object
// with the ability to set a context for a request.
func NewGetClustersParamsWithContext(ctx context.Context) *GetClustersParams {
	return &GetClustersParams{
		Context: ctx,
	}
}

// NewGetClustersParamsWithHTTPClient creates a new GetClustersParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClustersParamsWithHTTPClient(client *http.Client) *GetClustersParams {
	return &GetClustersParams{
		HTTPClient: client,
	}
}

/*
GetClustersParams contains all the parameters to send to the API endpoint

	for the get clusters operation.

	Typically these are written to a http.Request.
*/
type GetClustersParams struct {

	// Authorization.
	//
	// Format: Bearer {access_token}
	Authorization string

	/* Limit.

	   Number of clusters to retrieve (default is 10)

	   Format: int32
	*/
	Limit *int32

	/* Offset.

	   Offset for pagination (default is 0)

	   Format: int32
	*/
	Offset *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get clusters params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClustersParams) WithDefaults() *GetClustersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get clusters params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClustersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get clusters params
func (o *GetClustersParams) WithTimeout(timeout time.Duration) *GetClustersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get clusters params
func (o *GetClustersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get clusters params
func (o *GetClustersParams) WithContext(ctx context.Context) *GetClustersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get clusters params
func (o *GetClustersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get clusters params
func (o *GetClustersParams) WithHTTPClient(client *http.Client) *GetClustersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get clusters params
func (o *GetClustersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get clusters params
func (o *GetClustersParams) WithAuthorization(authorization string) *GetClustersParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get clusters params
func (o *GetClustersParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithLimit adds the limit to the get clusters params
func (o *GetClustersParams) WithLimit(limit *int32) *GetClustersParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get clusters params
func (o *GetClustersParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the get clusters params
func (o *GetClustersParams) WithOffset(offset *int32) *GetClustersParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get clusters params
func (o *GetClustersParams) SetOffset(offset *int32) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetClustersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
