// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pgEdge/terraform-provider-pgedge/client/models"
)

// GetCloudAccountsIDReader is a Reader for the GetCloudAccountsID structure.
type GetCloudAccountsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCloudAccountsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCloudAccountsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetCloudAccountsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetCloudAccountsIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /cloud-accounts/{id}] GetCloudAccountsID", response, response.Code())
	}
}

// NewGetCloudAccountsIDOK creates a GetCloudAccountsIDOK with default headers values
func NewGetCloudAccountsIDOK() *GetCloudAccountsIDOK {
	return &GetCloudAccountsIDOK{}
}

/*
GetCloudAccountsIDOK describes a response with status code 200, with default header values.

Response containing the cloud account details.
*/
type GetCloudAccountsIDOK struct {
	Payload *models.CloudAccount
}

// IsSuccess returns true when this get cloud accounts Id o k response has a 2xx status code
func (o *GetCloudAccountsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get cloud accounts Id o k response has a 3xx status code
func (o *GetCloudAccountsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cloud accounts Id o k response has a 4xx status code
func (o *GetCloudAccountsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get cloud accounts Id o k response has a 5xx status code
func (o *GetCloudAccountsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get cloud accounts Id o k response a status code equal to that given
func (o *GetCloudAccountsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get cloud accounts Id o k response
func (o *GetCloudAccountsIDOK) Code() int {
	return 200
}

func (o *GetCloudAccountsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloud-accounts/{id}][%d] getCloudAccountsIdOK %s", 200, payload)
}

func (o *GetCloudAccountsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloud-accounts/{id}][%d] getCloudAccountsIdOK %s", 200, payload)
}

func (o *GetCloudAccountsIDOK) GetPayload() *models.CloudAccount {
	return o.Payload
}

func (o *GetCloudAccountsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCloudAccountsIDBadRequest creates a GetCloudAccountsIDBadRequest with default headers values
func NewGetCloudAccountsIDBadRequest() *GetCloudAccountsIDBadRequest {
	return &GetCloudAccountsIDBadRequest{}
}

/*
GetCloudAccountsIDBadRequest describes a response with status code 400, with default header values.

Bad request.
*/
type GetCloudAccountsIDBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get cloud accounts Id bad request response has a 2xx status code
func (o *GetCloudAccountsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cloud accounts Id bad request response has a 3xx status code
func (o *GetCloudAccountsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cloud accounts Id bad request response has a 4xx status code
func (o *GetCloudAccountsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get cloud accounts Id bad request response has a 5xx status code
func (o *GetCloudAccountsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get cloud accounts Id bad request response a status code equal to that given
func (o *GetCloudAccountsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get cloud accounts Id bad request response
func (o *GetCloudAccountsIDBadRequest) Code() int {
	return 400
}

func (o *GetCloudAccountsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloud-accounts/{id}][%d] getCloudAccountsIdBadRequest %s", 400, payload)
}

func (o *GetCloudAccountsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloud-accounts/{id}][%d] getCloudAccountsIdBadRequest %s", 400, payload)
}

func (o *GetCloudAccountsIDBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetCloudAccountsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCloudAccountsIDUnauthorized creates a GetCloudAccountsIDUnauthorized with default headers values
func NewGetCloudAccountsIDUnauthorized() *GetCloudAccountsIDUnauthorized {
	return &GetCloudAccountsIDUnauthorized{}
}

/*
GetCloudAccountsIDUnauthorized describes a response with status code 401, with default header values.

Authorization information is missing or invalid.
*/
type GetCloudAccountsIDUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this get cloud accounts Id unauthorized response has a 2xx status code
func (o *GetCloudAccountsIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get cloud accounts Id unauthorized response has a 3xx status code
func (o *GetCloudAccountsIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cloud accounts Id unauthorized response has a 4xx status code
func (o *GetCloudAccountsIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get cloud accounts Id unauthorized response has a 5xx status code
func (o *GetCloudAccountsIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get cloud accounts Id unauthorized response a status code equal to that given
func (o *GetCloudAccountsIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get cloud accounts Id unauthorized response
func (o *GetCloudAccountsIDUnauthorized) Code() int {
	return 401
}

func (o *GetCloudAccountsIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloud-accounts/{id}][%d] getCloudAccountsIdUnauthorized %s", 401, payload)
}

func (o *GetCloudAccountsIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cloud-accounts/{id}][%d] getCloudAccountsIdUnauthorized %s", 401, payload)
}

func (o *GetCloudAccountsIDUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetCloudAccountsIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
