// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetBackupStoresIDParams creates a new GetBackupStoresIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetBackupStoresIDParams() *GetBackupStoresIDParams {
	return &GetBackupStoresIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetBackupStoresIDParamsWithTimeout creates a new GetBackupStoresIDParams object
// with the ability to set a timeout on a request.
func NewGetBackupStoresIDParamsWithTimeout(timeout time.Duration) *GetBackupStoresIDParams {
	return &GetBackupStoresIDParams{
		timeout: timeout,
	}
}

// NewGetBackupStoresIDParamsWithContext creates a new GetBackupStoresIDParams object
// with the ability to set a context for a request.
func NewGetBackupStoresIDParamsWithContext(ctx context.Context) *GetBackupStoresIDParams {
	return &GetBackupStoresIDParams{
		Context: ctx,
	}
}

// NewGetBackupStoresIDParamsWithHTTPClient creates a new GetBackupStoresIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetBackupStoresIDParamsWithHTTPClient(client *http.Client) *GetBackupStoresIDParams {
	return &GetBackupStoresIDParams{
		HTTPClient: client,
	}
}

/*
GetBackupStoresIDParams contains all the parameters to send to the API endpoint

	for the get backup stores ID operation.

	Typically these are written to a http.Request.
*/
type GetBackupStoresIDParams struct {

	// Authorization.
	//
	// Format: Bearer {access_token}
	Authorization string

	/* ID.

	   The ID of the backup store to get.

	   Format: uuid
	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get backup stores ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBackupStoresIDParams) WithDefaults() *GetBackupStoresIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get backup stores ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetBackupStoresIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get backup stores ID params
func (o *GetBackupStoresIDParams) WithTimeout(timeout time.Duration) *GetBackupStoresIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get backup stores ID params
func (o *GetBackupStoresIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get backup stores ID params
func (o *GetBackupStoresIDParams) WithContext(ctx context.Context) *GetBackupStoresIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get backup stores ID params
func (o *GetBackupStoresIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get backup stores ID params
func (o *GetBackupStoresIDParams) WithHTTPClient(client *http.Client) *GetBackupStoresIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get backup stores ID params
func (o *GetBackupStoresIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get backup stores ID params
func (o *GetBackupStoresIDParams) WithAuthorization(authorization string) *GetBackupStoresIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get backup stores ID params
func (o *GetBackupStoresIDParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithID adds the id to the get backup stores ID params
func (o *GetBackupStoresIDParams) WithID(id strfmt.UUID) *GetBackupStoresIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get backup stores ID params
func (o *GetBackupStoresIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetBackupStoresIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
