// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pgEdge/terraform-provider-pgedge/models"
)

// NewPatchClustersIDParams creates a new PatchClustersIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchClustersIDParams() *PatchClustersIDParams {
	return &PatchClustersIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchClustersIDParamsWithTimeout creates a new PatchClustersIDParams object
// with the ability to set a timeout on a request.
func NewPatchClustersIDParamsWithTimeout(timeout time.Duration) *PatchClustersIDParams {
	return &PatchClustersIDParams{
		timeout: timeout,
	}
}

// NewPatchClustersIDParamsWithContext creates a new PatchClustersIDParams object
// with the ability to set a context for a request.
func NewPatchClustersIDParamsWithContext(ctx context.Context) *PatchClustersIDParams {
	return &PatchClustersIDParams{
		Context: ctx,
	}
}

// NewPatchClustersIDParamsWithHTTPClient creates a new PatchClustersIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchClustersIDParamsWithHTTPClient(client *http.Client) *PatchClustersIDParams {
	return &PatchClustersIDParams{
		HTTPClient: client,
	}
}

/*
PatchClustersIDParams contains all the parameters to send to the API endpoint

	for the patch clusters ID operation.

	Typically these are written to a http.Request.
*/
type PatchClustersIDParams struct {

	// Authorization.
	//
	// Format: Bearer {access_token}
	Authorization string

	/* Body.

	   Cluster update request body
	*/
	Body *models.ClusterUpdateRequest

	// ID.
	//
	// Format: uuid
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch clusters ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchClustersIDParams) WithDefaults() *PatchClustersIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch clusters ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchClustersIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch clusters ID params
func (o *PatchClustersIDParams) WithTimeout(timeout time.Duration) *PatchClustersIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch clusters ID params
func (o *PatchClustersIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch clusters ID params
func (o *PatchClustersIDParams) WithContext(ctx context.Context) *PatchClustersIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch clusters ID params
func (o *PatchClustersIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch clusters ID params
func (o *PatchClustersIDParams) WithHTTPClient(client *http.Client) *PatchClustersIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch clusters ID params
func (o *PatchClustersIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the patch clusters ID params
func (o *PatchClustersIDParams) WithAuthorization(authorization string) *PatchClustersIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the patch clusters ID params
func (o *PatchClustersIDParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the patch clusters ID params
func (o *PatchClustersIDParams) WithBody(body *models.ClusterUpdateRequest) *PatchClustersIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch clusters ID params
func (o *PatchClustersIDParams) SetBody(body *models.ClusterUpdateRequest) {
	o.Body = body
}

// WithID adds the id to the patch clusters ID params
func (o *PatchClustersIDParams) WithID(id strfmt.UUID) *PatchClustersIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch clusters ID params
func (o *PatchClustersIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchClustersIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
