// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostOauthTokenParams creates a new PostOauthTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostOauthTokenParams() *PostOauthTokenParams {
	return &PostOauthTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostOauthTokenParamsWithTimeout creates a new PostOauthTokenParams object
// with the ability to set a timeout on a request.
func NewPostOauthTokenParamsWithTimeout(timeout time.Duration) *PostOauthTokenParams {
	return &PostOauthTokenParams{
		timeout: timeout,
	}
}

// NewPostOauthTokenParamsWithContext creates a new PostOauthTokenParams object
// with the ability to set a context for a request.
func NewPostOauthTokenParamsWithContext(ctx context.Context) *PostOauthTokenParams {
	return &PostOauthTokenParams{
		Context: ctx,
	}
}

// NewPostOauthTokenParamsWithHTTPClient creates a new PostOauthTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostOauthTokenParamsWithHTTPClient(client *http.Client) *PostOauthTokenParams {
	return &PostOauthTokenParams{
		HTTPClient: client,
	}
}

/*
PostOauthTokenParams contains all the parameters to send to the API endpoint

	for the post oauth token operation.

	Typically these are written to a http.Request.
*/
type PostOauthTokenParams struct {

	/* Body.

	   Client credentials for obtaining the OAuth token
	*/
	Body PostOauthTokenBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post oauth token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOauthTokenParams) WithDefaults() *PostOauthTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post oauth token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOauthTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post oauth token params
func (o *PostOauthTokenParams) WithTimeout(timeout time.Duration) *PostOauthTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post oauth token params
func (o *PostOauthTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post oauth token params
func (o *PostOauthTokenParams) WithContext(ctx context.Context) *PostOauthTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post oauth token params
func (o *PostOauthTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post oauth token params
func (o *PostOauthTokenParams) WithHTTPClient(client *http.Client) *PostOauthTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post oauth token params
func (o *PostOauthTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post oauth token params
func (o *PostOauthTokenParams) WithBody(body PostOauthTokenBody) *PostOauthTokenParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post oauth token params
func (o *PostOauthTokenParams) SetBody(body PostOauthTokenBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostOauthTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
