// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostDatabasesIDReplicationParams creates a new PostDatabasesIDReplicationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDatabasesIDReplicationParams() *PostDatabasesIDReplicationParams {
	return &PostDatabasesIDReplicationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDatabasesIDReplicationParamsWithTimeout creates a new PostDatabasesIDReplicationParams object
// with the ability to set a timeout on a request.
func NewPostDatabasesIDReplicationParamsWithTimeout(timeout time.Duration) *PostDatabasesIDReplicationParams {
	return &PostDatabasesIDReplicationParams{
		timeout: timeout,
	}
}

// NewPostDatabasesIDReplicationParamsWithContext creates a new PostDatabasesIDReplicationParams object
// with the ability to set a context for a request.
func NewPostDatabasesIDReplicationParamsWithContext(ctx context.Context) *PostDatabasesIDReplicationParams {
	return &PostDatabasesIDReplicationParams{
		Context: ctx,
	}
}

// NewPostDatabasesIDReplicationParamsWithHTTPClient creates a new PostDatabasesIDReplicationParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDatabasesIDReplicationParamsWithHTTPClient(client *http.Client) *PostDatabasesIDReplicationParams {
	return &PostDatabasesIDReplicationParams{
		HTTPClient: client,
	}
}

/*
PostDatabasesIDReplicationParams contains all the parameters to send to the API endpoint

	for the post databases ID replication operation.

	Typically these are written to a http.Request.
*/
type PostDatabasesIDReplicationParams struct {

	// Authorization.
	//
	// Format: Bearer {access_token}
	Authorization string

	// ID.
	//
	// Format: uuid
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post databases ID replication params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDatabasesIDReplicationParams) WithDefaults() *PostDatabasesIDReplicationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post databases ID replication params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDatabasesIDReplicationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post databases ID replication params
func (o *PostDatabasesIDReplicationParams) WithTimeout(timeout time.Duration) *PostDatabasesIDReplicationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post databases ID replication params
func (o *PostDatabasesIDReplicationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post databases ID replication params
func (o *PostDatabasesIDReplicationParams) WithContext(ctx context.Context) *PostDatabasesIDReplicationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post databases ID replication params
func (o *PostDatabasesIDReplicationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post databases ID replication params
func (o *PostDatabasesIDReplicationParams) WithHTTPClient(client *http.Client) *PostDatabasesIDReplicationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post databases ID replication params
func (o *PostDatabasesIDReplicationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post databases ID replication params
func (o *PostDatabasesIDReplicationParams) WithAuthorization(authorization string) *PostDatabasesIDReplicationParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post databases ID replication params
func (o *PostDatabasesIDReplicationParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithID adds the id to the post databases ID replication params
func (o *PostDatabasesIDReplicationParams) WithID(id strfmt.UUID) *PostDatabasesIDReplicationParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post databases ID replication params
func (o *PostDatabasesIDReplicationParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostDatabasesIDReplicationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
