// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pgEdge/terraform-provider-pgedge/client/models"
)

// PostDatabasesIDReplicateReader is a Reader for the PostDatabasesIDReplicate structure.
type PostDatabasesIDReplicateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDatabasesIDReplicateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDatabasesIDReplicateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostDatabasesIDReplicateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostDatabasesIDReplicateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDatabasesIDReplicateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /databases/{id}/replicate] PostDatabasesIDReplicate", response, response.Code())
	}
}

// NewPostDatabasesIDReplicateOK creates a PostDatabasesIDReplicateOK with default headers values
func NewPostDatabasesIDReplicateOK() *PostDatabasesIDReplicateOK {
	return &PostDatabasesIDReplicateOK{}
}

/*
PostDatabasesIDReplicateOK describes a response with status code 200, with default header values.

Successful response
*/
type PostDatabasesIDReplicateOK struct {
	Payload *models.ReplicationResponse
}

// IsSuccess returns true when this post databases Id replicate o k response has a 2xx status code
func (o *PostDatabasesIDReplicateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post databases Id replicate o k response has a 3xx status code
func (o *PostDatabasesIDReplicateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post databases Id replicate o k response has a 4xx status code
func (o *PostDatabasesIDReplicateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post databases Id replicate o k response has a 5xx status code
func (o *PostDatabasesIDReplicateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post databases Id replicate o k response a status code equal to that given
func (o *PostDatabasesIDReplicateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post databases Id replicate o k response
func (o *PostDatabasesIDReplicateOK) Code() int {
	return 200
}

func (o *PostDatabasesIDReplicateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /databases/{id}/replicate][%d] postDatabasesIdReplicateOK %s", 200, payload)
}

func (o *PostDatabasesIDReplicateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /databases/{id}/replicate][%d] postDatabasesIdReplicateOK %s", 200, payload)
}

func (o *PostDatabasesIDReplicateOK) GetPayload() *models.ReplicationResponse {
	return o.Payload
}

func (o *PostDatabasesIDReplicateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReplicationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDatabasesIDReplicateUnauthorized creates a PostDatabasesIDReplicateUnauthorized with default headers values
func NewPostDatabasesIDReplicateUnauthorized() *PostDatabasesIDReplicateUnauthorized {
	return &PostDatabasesIDReplicateUnauthorized{}
}

/*
PostDatabasesIDReplicateUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostDatabasesIDReplicateUnauthorized struct {
}

// IsSuccess returns true when this post databases Id replicate unauthorized response has a 2xx status code
func (o *PostDatabasesIDReplicateUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post databases Id replicate unauthorized response has a 3xx status code
func (o *PostDatabasesIDReplicateUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post databases Id replicate unauthorized response has a 4xx status code
func (o *PostDatabasesIDReplicateUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post databases Id replicate unauthorized response has a 5xx status code
func (o *PostDatabasesIDReplicateUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post databases Id replicate unauthorized response a status code equal to that given
func (o *PostDatabasesIDReplicateUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post databases Id replicate unauthorized response
func (o *PostDatabasesIDReplicateUnauthorized) Code() int {
	return 401
}

func (o *PostDatabasesIDReplicateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/replicate][%d] postDatabasesIdReplicateUnauthorized", 401)
}

func (o *PostDatabasesIDReplicateUnauthorized) String() string {
	return fmt.Sprintf("[POST /databases/{id}/replicate][%d] postDatabasesIdReplicateUnauthorized", 401)
}

func (o *PostDatabasesIDReplicateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostDatabasesIDReplicateNotFound creates a PostDatabasesIDReplicateNotFound with default headers values
func NewPostDatabasesIDReplicateNotFound() *PostDatabasesIDReplicateNotFound {
	return &PostDatabasesIDReplicateNotFound{}
}

/*
PostDatabasesIDReplicateNotFound describes a response with status code 404, with default header values.

Database not found
*/
type PostDatabasesIDReplicateNotFound struct {
}

// IsSuccess returns true when this post databases Id replicate not found response has a 2xx status code
func (o *PostDatabasesIDReplicateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post databases Id replicate not found response has a 3xx status code
func (o *PostDatabasesIDReplicateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post databases Id replicate not found response has a 4xx status code
func (o *PostDatabasesIDReplicateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post databases Id replicate not found response has a 5xx status code
func (o *PostDatabasesIDReplicateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post databases Id replicate not found response a status code equal to that given
func (o *PostDatabasesIDReplicateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post databases Id replicate not found response
func (o *PostDatabasesIDReplicateNotFound) Code() int {
	return 404
}

func (o *PostDatabasesIDReplicateNotFound) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/replicate][%d] postDatabasesIdReplicateNotFound", 404)
}

func (o *PostDatabasesIDReplicateNotFound) String() string {
	return fmt.Sprintf("[POST /databases/{id}/replicate][%d] postDatabasesIdReplicateNotFound", 404)
}

func (o *PostDatabasesIDReplicateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostDatabasesIDReplicateInternalServerError creates a PostDatabasesIDReplicateInternalServerError with default headers values
func NewPostDatabasesIDReplicateInternalServerError() *PostDatabasesIDReplicateInternalServerError {
	return &PostDatabasesIDReplicateInternalServerError{}
}

/*
PostDatabasesIDReplicateInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostDatabasesIDReplicateInternalServerError struct {
}

// IsSuccess returns true when this post databases Id replicate internal server error response has a 2xx status code
func (o *PostDatabasesIDReplicateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post databases Id replicate internal server error response has a 3xx status code
func (o *PostDatabasesIDReplicateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post databases Id replicate internal server error response has a 4xx status code
func (o *PostDatabasesIDReplicateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post databases Id replicate internal server error response has a 5xx status code
func (o *PostDatabasesIDReplicateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post databases Id replicate internal server error response a status code equal to that given
func (o *PostDatabasesIDReplicateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post databases Id replicate internal server error response
func (o *PostDatabasesIDReplicateInternalServerError) Code() int {
	return 500
}

func (o *PostDatabasesIDReplicateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /databases/{id}/replicate][%d] postDatabasesIdReplicateInternalServerError", 500)
}

func (o *PostDatabasesIDReplicateInternalServerError) String() string {
	return fmt.Sprintf("[POST /databases/{id}/replicate][%d] postDatabasesIdReplicateInternalServerError", 500)
}

func (o *PostDatabasesIDReplicateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
